import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const interSans = localFont({
  src: "./fonts/Inter.woff",
  variable: "--font-inter",
  weight: "400, 700",
});

const loraSerif = localFont({
  src: "./fonts/Lora.woff",
  variable: "--font-lora",
  weight: "400, 700",
});

const inconsolataMono = localFont({
  src: "./fonts/Inconsolata.woff",
  variable: "--font-inconsolata",
  weight: "400, 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${loraSerif.variable} ${inconsolataMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
